Repository open-rpc/schema-utils-js, pull requests merged in 2019-06, with the labels that each got.

#142 Fix/semantic release deps
  .circleci/config.yml
  package-lock.json
  package.json
Labels: enhancement

#147 fix: validate optional params
  package-lock.json
  src/method-call-validator/method-call-validator.test.ts
  src/method-call-validator/method-call-validator.ts
Labels: bug

#145 fix: remove semantic release deps
  package.json
Labels: bug

#157 feat(MethodCallValidator): add method not found error
  src/index-web.ts
  src/method-call-validator/method-call-validator.test.ts
  src/method-call-validator/method-call-validator.ts
  src/method-call-validator/method-not-found-error.test.ts
  src/method-call-validator/method-not-found-error.ts
  src/method-call-validator/parameter-validation-error.ts
Labels: bug, enhancement

#158 feat(MethodCallValidator): allow rpc discover
  src/method-call-validator/method-call-validator.test.ts
  src/method-call-validator/method-call-validator.ts
Labels: bug

#159 fix: update exports
  src/index.ts
  src/method-call-validator/index.ts
  src/method-call-validator/method-not-found-error.test.ts
  src/method-call-validator/method-not-found-error.ts
  src/method-call-validator/parameter-validation-error.ts
Labels: bug
